#!/usr/bin/env node

/**
 * Standalone PR Review Script
 * Reads diff from stdin, generates review, posts comment via GitHub API
 * Used by GitHub Actions - no MCP protocol overhead
 */

import { commentOnPR } from './github-api.js';

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const PR_NUMBER = parseInt(process.env.PR_NUMBER);
const REPO_OWNER = process.env.REPO_OWNER;
const REPO_NAME = process.env.REPO_NAME;

if (!GITHUB_TOKEN || !PR_NUMBER || !REPO_OWNER || !REPO_NAME) {
  console.error('Error: Missing required environment variables');
  console.error('Required: GITHUB_TOKEN, PR_NUMBER, REPO_OWNER, REPO_NAME');
  process.exit(1);
}

// Read diff from stdin
let diffContent = '';
process.stdin.on('data', (chunk) => {
  diffContent += chunk.toString();
});

process.stdin.on('end', async () => {
  try {
    // Analyze the diff
    const stats = analyzeDiff(diffContent);

    // Generate review comment
    const reviewComment = generateReview(stats, diffContent);

    // Post comment via GitHub API
    const result = await commentOnPR({
      token: GITHUB_TOKEN,
      owner: REPO_OWNER,
      repo: REPO_NAME,
      pr_number: PR_NUMBER,
      body: reviewComment
    });

    console.log('✓ Review posted successfully!');
    console.log(result.message);
    process.exit(0);
  } catch (error) {
    console.error('Error posting review:', error.message);
    process.exit(1);
  }
});

/**
 * Analyze diff and extract statistics
 */
function analyzeDiff(diff) {
  const lines = diff.split('\n');
  const stats = {
    filesChanged: new Set(),
    additions: 0,
    deletions: 0,
    hasTests: false,
    hasDocChanges: false
  };

  for (const line of lines) {
    if (line.startsWith('diff --git')) {
      const match = line.match(/b\/(.*?)$/);
      if (match) stats.filesChanged.add(match[1]);
    }
    if (line.startsWith('+') && !line.startsWith('+++')) stats.additions++;
    if (line.startsWith('-') && !line.startsWith('---')) stats.deletions++;
    if (line.includes('test.js') || line.includes('.test.') || line.includes('.spec.')) {
      stats.hasTests = true;
    }
    if (line.includes('README') || line.includes('.md')) {
      stats.hasDocChanges = true;
    }
  }

  return {
    filesChanged: Array.from(stats.filesChanged),
    additions: stats.additions,
    deletions: stats.deletions,
    hasTests: stats.hasTests,
    hasDocChanges: stats.hasDocChanges
  };
}

/**
 * Generate review comment markdown
 */
function generateReview(stats, diff) {
  let review = '## 🤖 Automated Code Review\n\n';
  review += '### 📊 Change Summary\n';
  review += `- **Files changed:** ${stats.filesChanged.length}\n`;
  review += `- **Lines added:** +${stats.additions}\n`;
  review += `- **Lines removed:** -${stats.deletions}\n`;
  review += `- **Net change:** ${stats.additions - stats.deletions > 0 ? '+' : ''}${stats.additions - stats.deletions}\n\n`;

  review += '### 📝 Modified Files\n';
  stats.filesChanged.forEach(file => {
    review += `- \`${file}\`\n`;
  });
  review += '\n';

  review += '### ✅ Checks\n';
  review += stats.hasTests ? '- ✅ Test files included\n' : '- ⚠️ No test files detected\n';
  review += stats.hasDocChanges ? '- ✅ Documentation updated\n' : '- ℹ️ No documentation changes\n';
  review += '\n';

  if (stats.deletions > stats.additions * 2) {
    review += '### 🎉 Cleanup PR\n';
    review += 'This PR removes more code than it adds - nice cleanup work!\n\n';
  }

  review += '---\n';
  review += '*This review was automatically generated by the GitHub MCP server*';

  return review;
}
